import { MenuItem, MenuCategory } from '@/types';

// All menu items exactly as shown on the Vakulaa Tiffins menu card
// Real food images sourced from Unsplash (commercially usable)
export const MENU_ITEMS: MenuItem[] = [
  // ── BREAKFAST CLASSICS ──────────────────────────────────────────
  {
    id: 'idly-2pc',
    name: 'Idly (2pc)',
    price: 40,
    category: 'breakfast',
    description: 'Soft steamed rice cakes served with coconut chutney and sambar',
    imageUrl: 'https://t3.ftcdn.net/jpg/03/62/02/26/360_F_362022640_fZ6UM0JycJlFDdBiR1pYlNddKfdGvYwR.jpg',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'ghee-idly-2pc',
    name: 'Ghee Idly (2pc)',
    price: 50,
    category: 'breakfast',
    description: 'Fluffy steamed idlis drizzled with pure desi ghee',
    imageUrl: 'https://i.pinimg.com/736x/16/f5/96/16f596c2f28b068cc2df93de7bd07a2a.jpg',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'vada-2pc',
    name: 'Vada (2pc)',
    price: 50,
    category: 'breakfast',
    description: 'Crispy urad dal fritters – golden outside, fluffy inside',
    imageUrl: 'https://www.chefkunalkapur.com/wp-content/uploads/2021/06/Medu-Vada-1300x867.jpg?v=1623509746',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'upma',
    name: 'Upma',
    price: 60,
    category: 'breakfast',
    description: 'Savory semolina porridge cooked with vegetables and spices',
    imageUrl: 'https://rakskitchen.net/wp-content/uploads/2013/02/upma-recipe-feat.jpg',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'pongal',
    name: 'Pongal',
    price: 70,
    category: 'breakfast',
    description: 'Comforting rice and moong dal porridge with pepper, ginger and ghee',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK4qsbydxwc_QUbnR74MVqShWIlTY6dO9aejapdY_Y3cpmxEZGVvmEKbc&s=10',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'poori',
    name: 'Poori',
    price: 70,
    category: 'breakfast',
    description: 'Puffed whole wheat bread served with spiced potato curry',
    imageUrl: 'https://www.awesomecuisine.com/wp-content/uploads/2020/03/poori-masala-kizhangu.jpg',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },

  // ── DOSA VARIETIES ───────────────────────────────────────────────
  {
    id: 'plain-dosa',
    name: 'Plain Dosa',
    price: 60,
    category: 'dosa',
    description: 'Classic thin crispy crepe made from fermented rice and lentil batter',
    imageUrl: 'https://www.awesomecuisine.com/wp-content/uploads/2009/06/Plain-Dosa.jpg',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    price: 70,
    category: 'dosa',
    description: 'Crispy dosa filled with spiced potato and onion masala',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvbskq5cxJNS2ypWRoZSN-gt4kHzB4Vqp9_XA0XuLCFDz_IiMymGZkOWs&s=10',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'onion-dosa',
    name: 'Onion Dosa',
    price: 80,
    category: 'dosa',
    description: 'Crispy dosa topped with finely chopped fresh onions',
    imageUrl: 'https://i.pinimg.com/originals/40/44/96/404496f23a3460b0c5e77cc833a181d0.jpg?nii=t',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'karam-dosa',
    name: 'Karam Dosa',
    price: 80,
    category: 'dosa',
    description: 'Spicy dosa spread with flavorful karam (chilli) chutney',
    imageUrl: 'https://d1w7312wesee68.cloudfront.net/tOf3k8S8i-3Ovb1mxT3gO7LU4i2Au86VrQNFXwfg-_Y/resize:fit:720:720/plain/s3://toasttab/restaurants/restaurant-223586000000000000/menu/items/0/item-1200000001293545530_1735938191.jpg',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'butter-plain-dosa',
    name: 'Butter Plain Dosa',
    price: 80,
    category: 'dosa',
    description: 'Golden crispy dosa enriched with a generous spread of butter',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkR60GWXIM3jDj_d4mJHt0xIRZXLlBBf9F4CdTpIwB0ZofknSpw9QIEqY&s=10',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ghee-karam-dosa',
    name: 'Ghee Karam Dosa',
    price: 90,
    category: 'dosa',
    description: 'Spicy karam dosa finished with aromatic desi ghee',
    imageUrl: 'https://homecookingshow.in/wp-content/uploads/2025/02/ghee-karam-dosa-1-1024x576.webp',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ghee-onion-dosa',
    name: 'Ghee Onion Dosa',
    price: 90,
    category: 'dosa',
    description: 'Onion dosa drizzled with rich ghee for extra indulgence',
    imageUrl: 'https://cdn.uengage.io/uploads/64296/image-4779-1758286029.jpg',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'upma-dosa',
    name: 'Upma Dosa',
    price: 90,
    category: 'dosa',
    description: 'Crispy dosa stuffed with savory upma filling',
    imageUrl: 'https://res.cloudinary.com/roundglass/image/upload/v1753187552/rg/collective/media/rg-food-in-upma-mla-pesarattu-rakesh-raghunathan-may2022-001-16x9-1753187551759.jpg',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'onion-masala-dosa',
    name: 'Onion Masala Dosa',
    price: 100,
    category: 'dosa',
    description: 'Crispy dosa with both onions and classic potato masala filling',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMqF7jDGZrT4uam2dNT56WX-5IBirp4yt-MK3IhaRmZxcuH2Cwz1g4eJE1&s=10',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'ghee-karam-masala-dosa',
    name: 'Ghee Karam Masala Dosa',
    price: 100,
    category: 'dosa',
    description: 'Spicy karam dosa with potato masala and a lavish ghee finish',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3EqUN83U1e6Af51Mf4igFDcyUu2T5wxB7_atZBqC21ieDt9xW7UcMpgQ&s=10',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'butter-masala-dosa',
    name: 'Butter Masala Dosa',
    price: 100,
    category: 'dosa',
    description: 'Classic masala dosa enriched with a generous layer of butter',
    imageUrl: 'https://5.imimg.com/data5/NB/FG/MY-33178756/paneer-butter-masala-dosa.png',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'open-butter-masala-dosa',
    name: 'Open Butter Masala Dosa',
    price: 110,
    category: 'dosa',
    description: 'Our signature dosa served open-face, loaded with masala and butter',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQY_javdF9qc1A-UgviYjOxJQYCqzuUF0WC5NiPJwIq8jefmhVklSnlsk&s=10',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },

  // ── BEVERAGES ────────────────────────────────────────────────────
  {
    id: 'coffee',
    name: 'Coffee',
    price: 30,
    category: 'beverages',
    description: 'South Indian filter coffee – rich, dark and deeply aromatic',
    imageUrl: 'https://img.magnific.com/free-photo/latte-coffee_1122-2728.jpg?semt=ais_hybrid&w=740&q=80',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'tea',
    name: 'Tea',
    price: 20,
    category: 'beverages',
    description: 'Hot masala chai brewed with ginger and aromatic spices',
    imageUrl: 'https://uzhavarbumi.s3.ap-south-1.amazonaws.com/uploads/at0X3L3commbLfoPRoWCfccwwGPT5RDmmGWkaxmb.jpg',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'water',
    name: 'Water (MRP)',
    price: 20,
    category: 'beverages',
    description: 'Chilled packaged drinking water',
    imageUrl: 'https://media.istockphoto.com/id/1373169040/photo/glass-of-fresh-pure-water-hard-light-deep-shadow.jpg?s=612x612&w=0&k=20&c=UYa_XhheOgFoENou8lZYFUPJdkxa4dMvQufGf7rSh_M=',
    isVeg: true,
    isAvailable: true,
  },
];

export const CATEGORIES: { id: MenuCategory | 'all'; label: string; emoji: string }[] = [
  { id: 'all', label: 'All Items', emoji: '🍽️' },
  { id: 'breakfast', label: 'Breakfast', emoji: '☀️' },
  { id: 'dosa', label: 'Dosa', emoji: '🫓' },
  { id: 'beverages', label: 'Beverages', emoji: '☕' },
];

export function getMenuByCategory(category: MenuCategory | 'all'): MenuItem[] {
  if (category === 'all') return MENU_ITEMS.filter(item => item.isAvailable);
  return MENU_ITEMS.filter(item => item.category === category && item.isAvailable);
}

export function getMenuItemById(id: string): MenuItem | undefined {
  return MENU_ITEMS.find(item => item.id === id);
}

// For AI chatbot – maps common spoken/written variations to item IDs
export const MENU_ALIASES: Record<string, string> = {
  'idly': 'idly-2pc',
  'idli': 'idly-2pc',
  'idlies': 'idly-2pc',
  'idlis': 'idly-2pc',
  'ghee idly': 'ghee-idly-2pc',
  'ghee idli': 'ghee-idly-2pc',
  'vada': 'vada-2pc',
  'wada': 'vada-2pc',
  'medu vada': 'vada-2pc',
  'upma': 'upma',
  'pongal': 'pongal',
  'khichdi': 'pongal',
  'poori': 'poori',
  'puri': 'poori',
  'bhatura': 'poori',
  'plain dosa': 'plain-dosa',
  'dosa': 'plain-dosa',
  'masala dosa': 'masala-dosa',
  'onion dosa': 'onion-dosa',
  'karam dosa': 'karam-dosa',
  'spicy dosa': 'karam-dosa',
  'butter plain dosa': 'butter-plain-dosa',
  'butter dosa': 'butter-plain-dosa',
  'ghee karam dosa': 'ghee-karam-dosa',
  'ghee onion dosa': 'ghee-onion-dosa',
  'upma dosa': 'upma-dosa',
  'onion masala dosa': 'onion-masala-dosa',
  'ghee karam masala dosa': 'ghee-karam-masala-dosa',
  'butter masala dosa': 'butter-masala-dosa',
  'open butter masala dosa': 'open-butter-masala-dosa',
  'open dosa': 'open-butter-masala-dosa',
  'coffee': 'coffee',
  'filter coffee': 'coffee',
  'kaapi': 'coffee',
  'tea': 'tea',
  'chai': 'tea',
  'water': 'water',
};

// Formatted menu for AI chatbot context
export const MENU_FOR_AI = MENU_ITEMS.map(
  item => `${item.name} - ₹${item.price === 0 ? 'MRP' : item.price}`
).join('\n');
