import { MenuItem, MenuCategory } from '@/types';

// All menu items exactly as shown on the Vakulaa Tiffins menu card
// Real food images sourced from Unsplash (commercially usable)
export const MENU_ITEMS: MenuItem[] = [
  // ── BREAKFAST CLASSICS ──────────────────────────────────────────
  {
    id: 'idly-2pc',
    name: 'Idly (2pc)',
    price: 40,
    category: 'breakfast',
    description: 'Soft steamed rice cakes served with coconut chutney and sambar',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'ghee-idly-2pc',
    name: 'Ghee Idly (2pc)',
    price: 50,
    category: 'breakfast',
    description: 'Fluffy steamed idlis drizzled with pure desi ghee',
    imageUrl: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'vada-2pc',
    name: 'Vada (2pc)',
    price: 50,
    category: 'breakfast',
    description: 'Crispy urad dal fritters – golden outside, fluffy inside',
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'upma',
    name: 'Upma',
    price: 60,
    category: 'breakfast',
    description: 'Savory semolina porridge cooked with vegetables and spices',
    imageUrl: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'pongal',
    name: 'Pongal',
    price: 70,
    category: 'breakfast',
    description: 'Comforting rice and moong dal porridge with pepper, ginger and ghee',
    imageUrl: 'https://images.unsplash.com/photo-1631292784640-848524e7f4b1?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'poori',
    name: 'Poori',
    price: 70,
    category: 'breakfast',
    description: 'Puffed whole wheat bread served with spiced potato curry',
    imageUrl: 'https://images.unsplash.com/photo-1605197788044-53866dde91e7?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },

  // ── DOSA VARIETIES ───────────────────────────────────────────────
  {
    id: 'plain-dosa',
    name: 'Plain Dosa',
    price: 60,
    category: 'dosa',
    description: 'Classic thin crispy crepe made from fermented rice and lentil batter',
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-47f2c23c97cc?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    price: 70,
    category: 'dosa',
    description: 'Crispy dosa filled with spiced potato and onion masala',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'onion-dosa',
    name: 'Onion Dosa',
    price: 80,
    category: 'dosa',
    description: 'Crispy dosa topped with finely chopped fresh onions',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'karam-dosa',
    name: 'Karam Dosa',
    price: 80,
    category: 'dosa',
    description: 'Spicy dosa spread with flavorful karam (chilli) chutney',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'butter-plain-dosa',
    name: 'Butter Plain Dosa',
    price: 80,
    category: 'dosa',
    description: 'Golden crispy dosa enriched with a generous spread of butter',
    imageUrl: 'https://images.unsplash.com/photo-1646090419895-6c05dc6a6cde?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ghee-karam-dosa',
    name: 'Ghee Karam Dosa',
    price: 90,
    category: 'dosa',
    description: 'Spicy karam dosa finished with aromatic desi ghee',
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-47f2c23c97cc?w=500&h=380&fit=crop&q=80&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ghee-onion-dosa',
    name: 'Ghee Onion Dosa',
    price: 90,
    category: 'dosa',
    description: 'Onion dosa drizzled with rich ghee for extra indulgence',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=380&fit=crop&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'upma-dosa',
    name: 'Upma Dosa',
    price: 90,
    category: 'dosa',
    description: 'Crispy dosa stuffed with savory upma filling',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&h=380&fit=crop&q=80',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'onion-masala-dosa',
    name: 'Onion Masala Dosa',
    price: 100,
    category: 'dosa',
    description: 'Crispy dosa with both onions and classic potato masala filling',
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&h=380&fit=crop&q=80',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'ghee-karam-masala-dosa',
    name: 'Ghee Karam Masala Dosa',
    price: 100,
    category: 'dosa',
    description: 'Spicy karam dosa with potato masala and a lavish ghee finish',
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-47f2c23c97cc?w=500&h=380&fit=crop',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'butter-masala-dosa',
    name: 'Butter Masala Dosa',
    price: 100,
    category: 'dosa',
    description: 'Classic masala dosa enriched with a generous layer of butter',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=380&fit=crop',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'open-butter-masala-dosa',
    name: 'Open Butter Masala Dosa',
    price: 110,
    category: 'dosa',
    description: 'Our signature dosa served open-face, loaded with masala and butter',
    imageUrl: 'https://images.unsplash.com/photo-1646090419895-6c05dc6a6cde?w=500&h=380&fit=crop',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },

  // ── BEVERAGES ────────────────────────────────────────────────────
  {
    id: 'coffee',
    name: 'Coffee',
    price: 30,
    category: 'beverages',
    description: 'South Indian filter coffee – rich, dark and deeply aromatic',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'tea',
    name: 'Tea',
    price: 20,
    category: 'beverages',
    description: 'Hot masala chai brewed with ginger and aromatic spices',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'water',
    name: 'Water',
    price: 0,
    category: 'beverages',
    description: 'Packaged drinking water (MRP)',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=380&fit=crop&auto=format',
    isVeg: true,
    isAvailable: true,
  },
];

export const CATEGORIES: { id: MenuCategory | 'all'; label: string; emoji: string }[] = [
  { id: 'all', label: 'All Items', emoji: '🍽️' },
  { id: 'breakfast', label: 'Breakfast', emoji: '☀️' },
  { id: 'dosa', label: 'Dosa', emoji: '🫓' },
  { id: 'beverages', label: 'Beverages', emoji: '☕' },
];

export function getMenuByCategory(category: MenuCategory | 'all'): MenuItem[] {
  if (category === 'all') return MENU_ITEMS.filter(item => item.isAvailable);
  return MENU_ITEMS.filter(item => item.category === category && item.isAvailable);
}

export function getMenuItemById(id: string): MenuItem | undefined {
  return MENU_ITEMS.find(item => item.id === id);
}

// For AI chatbot – maps common spoken/written variations to item IDs
export const MENU_ALIASES: Record<string, string> = {
  'idly': 'idly-2pc',
  'idli': 'idly-2pc',
  'idlies': 'idly-2pc',
  'idlis': 'idly-2pc',
  'ghee idly': 'ghee-idly-2pc',
  'ghee idli': 'ghee-idly-2pc',
  'vada': 'vada-2pc',
  'wada': 'vada-2pc',
  'medu vada': 'vada-2pc',
  'upma': 'upma',
  'pongal': 'pongal',
  'khichdi': 'pongal',
  'poori': 'poori',
  'puri': 'poori',
  'bhatura': 'poori',
  'plain dosa': 'plain-dosa',
  'dosa': 'plain-dosa',
  'masala dosa': 'masala-dosa',
  'onion dosa': 'onion-dosa',
  'karam dosa': 'karam-dosa',
  'spicy dosa': 'karam-dosa',
  'butter plain dosa': 'butter-plain-dosa',
  'butter dosa': 'butter-plain-dosa',
  'ghee karam dosa': 'ghee-karam-dosa',
  'ghee onion dosa': 'ghee-onion-dosa',
  'upma dosa': 'upma-dosa',
  'onion masala dosa': 'onion-masala-dosa',
  'ghee karam masala dosa': 'ghee-karam-masala-dosa',
  'butter masala dosa': 'butter-masala-dosa',
  'open butter masala dosa': 'open-butter-masala-dosa',
  'open dosa': 'open-butter-masala-dosa',
  'coffee': 'coffee',
  'filter coffee': 'coffee',
  'kaapi': 'coffee',
  'tea': 'tea',
  'chai': 'tea',
  'water': 'water',
};

// Formatted menu for AI chatbot context
export const MENU_FOR_AI = MENU_ITEMS.map(
  item => `${item.name} - ₹${item.price === 0 ? 'MRP' : item.price}`
).join('\n');
